"""add_alignment_fields_to_subtitle_files

Revision ID: 0491f989b581
Revises: c7d7accc4a66
Create Date: 2026-03-08 19:23:41.494873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0491f989b581'
down_revision: Union[str, None] = 'c7d7accc4a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtitle_files', sa.Column('alignment_source', sa.String(length=50), nullable=True))
    op.add_column('subtitle_files', sa.Column('alignment_confidence', sa.Float(), nullable=True))
    op.add_column('subtitle_files', sa.Column('alignment_matched', sa.Integer(), nullable=True))
    op.add_column('subtitle_files', sa.Column('alignment_total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subtitle_files', 'alignment_total')
    op.drop_column('subtitle_files', 'alignment_matched')
    op.drop_column('subtitle_files', 'alignment_confidence')
    op.drop_column('subtitle_files', 'alignment_source')
    # ### end Alembic commands ###
