"""add audio paths to songs

Revision ID: c7d7accc4a66
Revises: 526754d5882f
Create Date: 2026-03-08 18:35:40.627574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7d7accc4a66'
down_revision: Union[str, None] = '526754d5882f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('audio_path', sa.String(length=500), nullable=True))
    op.add_column('songs', sa.Column('vocals_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'vocals_path')
    op.drop_column('songs', 'audio_path')
    # ### end Alembic commands ###
