"""add confidence source_type to subtitle_lines and alignment_algorithm to subtitle_files

Revision ID: cfaed96ff84b
Revises: 0491f989b581
Create Date: 2026-03-08 20:15:07.267169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfaed96ff84b'
down_revision: Union[str, None] = '0491f989b581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtitle_files', sa.Column('alignment_algorithm', sa.String(length=20), nullable=True))
    op.add_column('subtitle_lines', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('subtitle_lines', sa.Column('source_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subtitle_lines', 'source_type')
    op.drop_column('subtitle_lines', 'confidence')
    op.drop_column('subtitle_files', 'alignment_algorithm')
    # ### end Alembic commands ###
